function R = Generate_R(alpha,beta,gamma)
%GENERATE_R
%    R = GENERATE_R(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    31-Aug-2016 21:41:10

t2 = cos(beta);
t3 = sin(gamma);
t4 = cos(gamma);
t5 = sin(alpha);
t6 = sin(beta);
t7 = cos(alpha);
R = reshape([t2.*t4+t3.*t5.*t6,t3.*t7,-t4.*t6+t2.*t3.*t5,-t2.*t3+t4.*t5.*t6,t4.*t7,t3.*t6+t2.*t4.*t5,t6.*t7,-t5,t2.*t7],[3,3]);
