function TP_dot = Generate_TP_dot(TP1_1,TP1_2,TP1_3,TP1_4,TP1_5,TP1_6,TP2_1,TP2_2,TP2_3,TP2_4,TP2_5,TP2_6,TP3_1,TP3_2,TP3_3,TP3_4,TP3_5,TP3_6,alpha,alpha_dot,beta,beta_dot,gamma,gamma_dot,x_dot,y_dot,z_dot)
%GENERATE_TP_DOT
%    TP_DOT = GENERATE_TP_DOT(TP1_1,TP1_2,TP1_3,TP1_4,TP1_5,TP1_6,TP2_1,TP2_2,TP2_3,TP2_4,TP2_5,TP2_6,TP3_1,TP3_2,TP3_3,TP3_4,TP3_5,TP3_6,ALPHA,ALPHA_DOT,BETA,BETA_DOT,GAMMA,GAMMA_DOT,X_DOT,Y_DOT,Z_DOT)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    03-Oct-2016 12:02:20

t2 = sin(beta);
t3 = sin(gamma);
t4 = cos(beta);
t5 = cos(gamma);
t6 = sin(alpha);
t7 = cos(alpha);
t8 = t2.*t5;
t18 = t3.*t4.*t6;
t9 = t8-t18;
t10 = t2.*t3;
t11 = t4.*t5.*t6;
t12 = t10+t11;
t13 = t3.*t4;
t19 = t2.*t5.*t6;
t14 = t13-t19;
t15 = t4.*t5;
t16 = t2.*t3.*t6;
t17 = t15+t16;
TP_dot = reshape([x_dot+beta_dot.*(-TP1_1.*t9+TP2_1.*t12+TP3_1.*t4.*t7)-gamma_dot.*(TP1_1.*t14+TP2_1.*t17)+alpha_dot.*(-TP3_1.*t2.*t6+TP1_1.*t2.*t3.*t7+TP2_1.*t2.*t5.*t7),y_dot+gamma_dot.*(TP1_1.*t5.*t7-TP2_1.*t3.*t7)-alpha_dot.*(TP3_1.*t7+TP1_1.*t3.*t6+TP2_1.*t5.*t6),z_dot-beta_dot.*(TP1_1.*t17-TP2_1.*t14+TP3_1.*t2.*t7)+gamma_dot.*(TP1_1.*t12+TP2_1.*t9)+alpha_dot.*(-TP3_1.*t4.*t6+TP1_1.*t3.*t4.*t7+TP2_1.*t4.*t5.*t7),x_dot+beta_dot.*(-TP1_2.*t9+TP2_2.*t12+TP3_2.*t4.*t7)-gamma_dot.*(TP1_2.*t14+TP2_2.*t17)+alpha_dot.*(-TP3_2.*t2.*t6+TP1_2.*t2.*t3.*t7+TP2_2.*t2.*t5.*t7),y_dot+gamma_dot.*(TP1_2.*t5.*t7-TP2_2.*t3.*t7)-alpha_dot.*(TP3_2.*t7+TP1_2.*t3.*t6+TP2_2.*t5.*t6),z_dot-beta_dot.*(TP1_2.*t17-TP2_2.*t14+TP3_2.*t2.*t7)+gamma_dot.*(TP1_2.*t12+TP2_2.*t9)+alpha_dot.*(-TP3_2.*t4.*t6+TP1_2.*t3.*t4.*t7+TP2_2.*t4.*t5.*t7),x_dot+beta_dot.*(-TP1_3.*t9+TP2_3.*t12+TP3_3.*t4.*t7)-gamma_dot.*(TP1_3.*t14+TP2_3.*t17)+alpha_dot.*(-TP3_3.*t2.*t6+TP1_3.*t2.*t3.*t7+TP2_3.*t2.*t5.*t7),y_dot+gamma_dot.*(TP1_3.*t5.*t7-TP2_3.*t3.*t7)-alpha_dot.*(TP3_3.*t7+TP1_3.*t3.*t6+TP2_3.*t5.*t6),z_dot-beta_dot.*(TP1_3.*t17-TP2_3.*t14+TP3_3.*t2.*t7)+gamma_dot.*(TP1_3.*t12+TP2_3.*t9)+alpha_dot.*(-TP3_3.*t4.*t6+TP1_3.*t3.*t4.*t7+TP2_3.*t4.*t5.*t7),x_dot+beta_dot.*(-TP1_4.*t9+TP2_4.*t12+TP3_4.*t4.*t7)-gamma_dot.*(TP1_4.*t14+TP2_4.*t17)+alpha_dot.*(-TP3_4.*t2.*t6+TP1_4.*t2.*t3.*t7+TP2_4.*t2.*t5.*t7),y_dot+gamma_dot.*(TP1_4.*t5.*t7-TP2_4.*t3.*t7)-alpha_dot.*(TP3_4.*t7+TP1_4.*t3.*t6+TP2_4.*t5.*t6),z_dot-beta_dot.*(TP1_4.*t17-TP2_4.*t14+TP3_4.*t2.*t7)+gamma_dot.*(TP1_4.*t12+TP2_4.*t9)+alpha_dot.*(-TP3_4.*t4.*t6+TP1_4.*t3.*t4.*t7+TP2_4.*t4.*t5.*t7),x_dot+beta_dot.*(-TP1_5.*t9+TP2_5.*t12+TP3_5.*t4.*t7)-gamma_dot.*(TP1_5.*t14+TP2_5.*t17)+alpha_dot.*(-TP3_5.*t2.*t6+TP1_5.*t2.*t3.*t7+TP2_5.*t2.*t5.*t7),y_dot+gamma_dot.*(TP1_5.*t5.*t7-TP2_5.*t3.*t7)-alpha_dot.*(TP3_5.*t7+TP1_5.*t3.*t6+TP2_5.*t5.*t6),z_dot-beta_dot.*(TP1_5.*t17-TP2_5.*t14+TP3_5.*t2.*t7)+gamma_dot.*(TP1_5.*t12+TP2_5.*t9)+alpha_dot.*(-TP3_5.*t4.*t6+TP1_5.*t3.*t4.*t7+TP2_5.*t4.*t5.*t7),x_dot+beta_dot.*(-TP1_6.*t9+TP2_6.*t12+TP3_6.*t4.*t7)-gamma_dot.*(TP1_6.*t14+TP2_6.*t17)+alpha_dot.*(-TP3_6.*t2.*t6+TP1_6.*t2.*t3.*t7+TP2_6.*t2.*t5.*t7),y_dot+gamma_dot.*(TP1_6.*t5.*t7-TP2_6.*t3.*t7)-alpha_dot.*(TP3_6.*t7+TP1_6.*t3.*t6+TP2_6.*t5.*t6),z_dot-beta_dot.*(TP1_6.*t17-TP2_6.*t14+TP3_6.*t2.*t7)+gamma_dot.*(TP1_6.*t12+TP2_6.*t9)+alpha_dot.*(-TP3_6.*t4.*t6+TP1_6.*t3.*t4.*t7+TP2_6.*t4.*t5.*t7)],[3,6]);
