function theta_glob = Generate_Theta_Glob(TP1_1,TP1_2,TP1_3,TP1_4,TP1_5,TP1_6,TP2_1,TP2_2,TP2_3,TP2_4,TP2_5,TP2_6,TP3_1,TP3_2,TP3_3,TP3_4,TP3_5,TP3_6,alpha,beta,gamma,x,xb1,xb2,xb3,xb4,xb5,xb6,y,yb1,yb2,yb3,yb4,yb5,yb6)
%GENERATE_THETA_GLOB
%    THETA_GLOB = GENERATE_THETA_GLOB(TP1_1,TP1_2,TP1_3,TP1_4,TP1_5,TP1_6,TP2_1,TP2_2,TP2_3,TP2_4,TP2_5,TP2_6,TP3_1,TP3_2,TP3_3,TP3_4,TP3_5,TP3_6,ALPHA,BETA,GAMMA,X,XB1,XB2,XB3,XB4,XB5,XB6,Y,YB1,YB2,YB3,YB4,YB5,YB6)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    03-Oct-2016 12:02:25

t2 = sin(alpha);
t3 = cos(beta);
t4 = sin(gamma);
t5 = cos(gamma);
t6 = sin(beta);
t7 = cos(alpha);
t8 = y.*1i;
t9 = t3.*t5;
t10 = t2.*t4.*t6;
t11 = t9+t10;
t12 = t3.*t4;
t14 = t2.*t5.*t6;
t13 = t12-t14;
theta_glob = [angle(t8+x-xb1-yb1.*1i+TP1_1.*t11-TP3_1.*t2.*1i-TP2_1.*t13+TP1_1.*t4.*t7.*1i+TP2_1.*t5.*t7.*1i+TP3_1.*t6.*t7),angle(t8+x-xb2-yb2.*1i+TP1_2.*t11-TP3_2.*t2.*1i-TP2_2.*t13+TP1_2.*t4.*t7.*1i+TP2_2.*t5.*t7.*1i+TP3_2.*t6.*t7),angle(t8+x-xb3-yb3.*1i+TP1_3.*t11-TP3_3.*t2.*1i-TP2_3.*t13+TP1_3.*t4.*t7.*1i+TP2_3.*t5.*t7.*1i+TP3_3.*t6.*t7),angle(t8+x-xb4-yb4.*1i+TP1_4.*t11-TP3_4.*t2.*1i-TP2_4.*t13+TP1_4.*t4.*t7.*1i+TP2_4.*t5.*t7.*1i+TP3_4.*t6.*t7),angle(t8+x-xb5-yb5.*1i+TP1_5.*t11-TP3_5.*t2.*1i-TP2_5.*t13+TP1_5.*t4.*t7.*1i+TP2_5.*t5.*t7.*1i+TP3_5.*t6.*t7),angle(t8+x-xb6-yb6.*1i+TP1_6.*t11-TP3_6.*t2.*1i-TP2_6.*t13+TP1_6.*t4.*t7.*1i+TP2_6.*t5.*t7.*1i+TP3_6.*t6.*t7)];
