function phi_glob = Generate_Phi_Glob(TP1_1,TP1_2,TP1_3,TP1_4,TP1_5,TP1_6,TP2_1,TP2_2,TP2_3,TP2_4,TP2_5,TP2_6,TP3_1,TP3_2,TP3_3,TP3_4,TP3_5,TP3_6,alpha,beta,gamma,x,xb1,xb2,xb3,xb4,xb5,xb6,y,yb1,yb2,yb3,yb4,yb5,yb6,z,zb1,zb2,zb3,zb4,zb5,zb6)
%GENERATE_PHI_GLOB
%    PHI_GLOB = GENERATE_PHI_GLOB(TP1_1,TP1_2,TP1_3,TP1_4,TP1_5,TP1_6,TP2_1,TP2_2,TP2_3,TP2_4,TP2_5,TP2_6,TP3_1,TP3_2,TP3_3,TP3_4,TP3_5,TP3_6,ALPHA,BETA,GAMMA,X,XB1,XB2,XB3,XB4,XB5,XB6,Y,YB1,YB2,YB3,YB4,YB5,YB6,Z,ZB1,ZB2,ZB3,ZB4,ZB5,ZB6)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    03-Oct-2016 12:02:52

t2 = cos(beta);
t3 = sin(gamma);
t4 = cos(gamma);
t5 = sin(alpha);
t6 = sin(beta);
t8 = cos(alpha);
t11 = t2.*t4;
t12 = t3.*t5.*t6;
t13 = t11+t12;
t14 = t2.*t3;
t15 = t4.*t5.*t6;
t16 = t14-t15;
t7 = x-xb1+TP1_1.*t13-TP2_1.*t16+TP3_1.*t6.*t8;
t9 = y-yb1-TP3_1.*t5+TP1_1.*t3.*t8+TP2_1.*t4.*t8;
t10 = z.*1i;
t17 = x-xb2+TP1_2.*t13-TP2_2.*t16+TP3_2.*t6.*t8;
t18 = y-yb2-TP3_2.*t5+TP1_2.*t3.*t8+TP2_2.*t4.*t8;
t19 = t4.*t6;
t26 = t2.*t3.*t5;
t20 = t19-t26;
t21 = t3.*t6;
t22 = t2.*t4.*t5;
t23 = t21+t22;
t24 = x-xb3+TP1_3.*t13-TP2_3.*t16+TP3_3.*t6.*t8;
t25 = y-yb3-TP3_3.*t5+TP1_3.*t3.*t8+TP2_3.*t4.*t8;
t27 = x-xb4+TP1_4.*t13-TP2_4.*t16+TP3_4.*t6.*t8;
t28 = y-yb4-TP3_4.*t5+TP1_4.*t3.*t8+TP2_4.*t4.*t8;
t29 = x-xb5+TP1_5.*t13-TP2_5.*t16+TP3_5.*t6.*t8;
t30 = y-yb5-TP3_5.*t5+TP1_5.*t3.*t8+TP2_5.*t4.*t8;
t31 = x-xb6+TP1_6.*t13-TP2_6.*t16+TP3_6.*t6.*t8;
t32 = y-yb6-TP3_6.*t5+TP1_6.*t3.*t8+TP2_6.*t4.*t8;
phi_glob = [angle(t10-zb1.*1i-TP1_1.*t20.*1i+TP2_1.*t23.*1i+sqrt(t7.^2+t9.^2)+TP3_1.*t2.*t8.*1i),angle(t10-zb2.*1i-TP1_2.*t20.*1i+TP2_2.*t23.*1i+sqrt(t17.^2+t18.^2)+TP3_2.*t2.*t8.*1i),angle(t10-zb3.*1i-TP1_3.*t20.*1i+TP2_3.*t23.*1i+sqrt(t24.^2+t25.^2)+TP3_3.*t2.*t8.*1i),angle(t10-zb4.*1i-TP1_4.*t20.*1i+TP2_4.*t23.*1i+sqrt(t27.^2+t28.^2)+TP3_4.*t2.*t8.*1i),angle(t10-zb5.*1i-TP1_5.*t20.*1i+TP2_5.*t23.*1i+sqrt(t29.^2+t30.^2)+TP3_5.*t2.*t8.*1i),angle(t10-zb6.*1i-TP1_6.*t20.*1i+TP2_6.*t23.*1i+sqrt(t31.^2+t32.^2)+TP3_6.*t2.*t8.*1i)];
