function theta = Generate_Theta(xb1,xb2,xb3,xb4,xb5,xb6,xt1,xt2,xt3,xt4,xt5,xt6,yb1,yb2,yb3,yb4,yb5,yb6,yt1,yt2,yt3,yt4,yt5,yt6)
%GENERATE_THETA
%    THETA = GENERATE_THETA(XB1,XB2,XB3,XB4,XB5,XB6,XT1,XT2,XT3,XT4,XT5,XT6,YB1,YB2,YB3,YB4,YB5,YB6,YT1,YT2,YT3,YT4,YT5,YT6)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    03-Oct-2016 12:02:24

theta = [angle(-xb1+xt1-yb1.*1i+yt1.*1i),angle(-xb2+xt2-yb2.*1i+yt2.*1i),angle(-xb3+xt3-yb3.*1i+yt3.*1i),angle(-xb4+xt4-yb4.*1i+yt4.*1i),angle(-xb5+xt5-yb5.*1i+yt5.*1i),angle(-xb6+xt6-yb6.*1i+yt6.*1i)];
