function out1 = Generate_Theta_Ddt(Fr1_1,Fr1_2,Fr1_3,Fr1_4,Fr1_5,Fr1_6,Fr2_1,Fr2_2,Fr2_3,Fr2_4,Fr2_5,Fr2_6,L_vector1_1,L_vector1_2,L_vector1_3,L_vector1_4,L_vector1_5,L_vector1_6,L_vector2_1,L_vector2_2,L_vector2_3,L_vector2_4,L_vector2_5,L_vector2_6,Prml2,Prmm1,Prmm2,Prmm3,d1dot_1,d1dot_2,d1dot_3,d1dot_4,d1dot_5,d1dot_6,d2dot_1,d2dot_2,d2dot_3,d2dot_4,d2dot_5,d2dot_6,r2_1,r2_2,r2_3,r2_4,r2_5,r2_6,r3_1,r3_2,r3_3,r3_4,r3_5,r3_6,t_phi1,t_phi2,t_phi3,t_phi4,t_phi5,t_phi6,t_phi_dot1,t_phi_dot2,t_phi_dot3,t_phi_dot4,t_phi_dot5,t_phi_dot6,t_theta_dot1,t_theta_dot2,t_theta_dot3,t_theta_dot4,t_theta_dot5,t_theta_dot6)
%GENERATE_THETA_DDT
%    OUT1 = GENERATE_THETA_DDT(FR1_1,FR1_2,FR1_3,FR1_4,FR1_5,FR1_6,FR2_1,FR2_2,FR2_3,FR2_4,FR2_5,FR2_6,L_VECTOR1_1,L_VECTOR1_2,L_VECTOR1_3,L_VECTOR1_4,L_VECTOR1_5,L_VECTOR1_6,L_VECTOR2_1,L_VECTOR2_2,L_VECTOR2_3,L_VECTOR2_4,L_VECTOR2_5,L_VECTOR2_6,PRML2,PRMM1,PRMM2,PRMM3,D1DOT_1,D1DOT_2,D1DOT_3,D1DOT_4,D1DOT_5,D1DOT_6,D2DOT_1,D2DOT_2,D2DOT_3,D2DOT_4,D2DOT_5,D2DOT_6,R2_1,R2_2,R2_3,R2_4,R2_5,R2_6,R3_1,R3_2,R3_3,R3_4,R3_5,R3_6,T_PHI1,T_PHI2,T_PHI3,T_PHI4,T_PHI5,T_PHI6,T_PHI_DOT1,T_PHI_DOT2,T_PHI_DOT3,T_PHI_DOT4,T_PHI_DOT5,T_PHI_DOT6,T_THETA_DOT1,T_THETA_DOT2,T_THETA_DOT3,T_THETA_DOT4,T_THETA_DOT5,T_THETA_DOT6)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    03-Oct-2016 12:04:29

t2 = r2_1.^2;
t3 = cos(t_phi1);
t4 = t3.^2;
t5 = Prml2.^2;
t6 = sin(t_phi1);
t7 = r3_1.^2;
t8 = Prmm1.*t5;
t9 = r2_2.^2;
t10 = cos(t_phi2);
t11 = t10.^2;
t12 = sin(t_phi2);
t13 = r3_2.^2;
t14 = r2_3.^2;
t15 = cos(t_phi3);
t16 = t15.^2;
t17 = sin(t_phi3);
t18 = r3_3.^2;
t19 = r2_4.^2;
t20 = cos(t_phi4);
t21 = t20.^2;
t22 = sin(t_phi4);
t23 = r3_4.^2;
t24 = r2_5.^2;
t25 = cos(t_phi5);
t26 = t25.^2;
t27 = sin(t_phi5);
t28 = r3_5.^2;
t29 = r2_6.^2;
t30 = cos(t_phi6);
t31 = t30.^2;
t32 = sin(t_phi6);
t33 = r3_6.^2;
out1 = [(1.0./t3.^2.*(Fr1_1.*L_vector2_1.*2.0-Fr2_1.*L_vector1_1.*2.0-Prml2.*Prmm1.*d1dot_1.*t4.*t_theta_dot1.*2.0+Prmm1.*d1dot_1.*r2_1.*t4.*t_theta_dot1.*2.0+Prmm2.*d1dot_1.*r2_1.*t4.*t_theta_dot1.*4.0+Prmm3.*d1dot_1.*r3_1.*t4.*t_theta_dot1.*4.0+Prmm3.*d2dot_1.*r3_1.*t4.*t_theta_dot1.*4.0-Prmm1.*t2.*t3.*t6.*t_phi_dot1.*t_theta_dot1-Prmm2.*t2.*t3.*t6.*t_phi_dot1.*t_theta_dot1.*4.0-Prmm1.*t3.*t5.*t6.*t_phi_dot1.*t_theta_dot1-Prmm3.*t3.*t6.*t7.*t_phi_dot1.*t_theta_dot1.*4.0+Prml2.*Prmm1.*r2_1.*t3.*t6.*t_phi_dot1.*t_theta_dot1.*2.0).*-2.0)./(t8+Prmm1.*t2+Prmm2.*t2.*4.0+Prmm3.*t7.*4.0-Prml2.*Prmm1.*r2_1.*2.0);(1.0./t10.^2.*(Fr1_2.*L_vector2_2.*2.0-Fr2_2.*L_vector1_2.*2.0-Prml2.*Prmm1.*d1dot_2.*t11.*t_theta_dot2.*2.0+Prmm1.*d1dot_2.*r2_2.*t11.*t_theta_dot2.*2.0+Prmm2.*d1dot_2.*r2_2.*t11.*t_theta_dot2.*4.0+Prmm3.*d1dot_2.*r3_2.*t11.*t_theta_dot2.*4.0+Prmm3.*d2dot_2.*r3_2.*t11.*t_theta_dot2.*4.0-Prmm1.*t5.*t10.*t12.*t_phi_dot2.*t_theta_dot2-Prmm1.*t9.*t10.*t12.*t_phi_dot2.*t_theta_dot2-Prmm2.*t9.*t10.*t12.*t_phi_dot2.*t_theta_dot2.*4.0-Prmm3.*t10.*t12.*t13.*t_phi_dot2.*t_theta_dot2.*4.0+Prml2.*Prmm1.*r2_2.*t10.*t12.*t_phi_dot2.*t_theta_dot2.*2.0).*-2.0)./(t8+Prmm1.*t9+Prmm2.*t9.*4.0+Prmm3.*t13.*4.0-Prml2.*Prmm1.*r2_2.*2.0);(1.0./t15.^2.*(Fr1_3.*L_vector2_3.*2.0-Fr2_3.*L_vector1_3.*2.0-Prml2.*Prmm1.*d1dot_3.*t16.*t_theta_dot3.*2.0+Prmm1.*d1dot_3.*r2_3.*t16.*t_theta_dot3.*2.0+Prmm2.*d1dot_3.*r2_3.*t16.*t_theta_dot3.*4.0+Prmm3.*d1dot_3.*r3_3.*t16.*t_theta_dot3.*4.0+Prmm3.*d2dot_3.*r3_3.*t16.*t_theta_dot3.*4.0-Prmm1.*t5.*t15.*t17.*t_phi_dot3.*t_theta_dot3-Prmm1.*t14.*t15.*t17.*t_phi_dot3.*t_theta_dot3-Prmm2.*t14.*t15.*t17.*t_phi_dot3.*t_theta_dot3.*4.0-Prmm3.*t15.*t17.*t18.*t_phi_dot3.*t_theta_dot3.*4.0+Prml2.*Prmm1.*r2_3.*t15.*t17.*t_phi_dot3.*t_theta_dot3.*2.0).*-2.0)./(t8+Prmm1.*t14+Prmm2.*t14.*4.0+Prmm3.*t18.*4.0-Prml2.*Prmm1.*r2_3.*2.0);(1.0./t20.^2.*(Fr1_4.*L_vector2_4.*2.0-Fr2_4.*L_vector1_4.*2.0-Prml2.*Prmm1.*d1dot_4.*t21.*t_theta_dot4.*2.0+Prmm1.*d1dot_4.*r2_4.*t21.*t_theta_dot4.*2.0+Prmm2.*d1dot_4.*r2_4.*t21.*t_theta_dot4.*4.0+Prmm3.*d1dot_4.*r3_4.*t21.*t_theta_dot4.*4.0+Prmm3.*d2dot_4.*r3_4.*t21.*t_theta_dot4.*4.0-Prmm1.*t5.*t20.*t22.*t_phi_dot4.*t_theta_dot4-Prmm1.*t19.*t20.*t22.*t_phi_dot4.*t_theta_dot4-Prmm2.*t19.*t20.*t22.*t_phi_dot4.*t_theta_dot4.*4.0-Prmm3.*t20.*t22.*t23.*t_phi_dot4.*t_theta_dot4.*4.0+Prml2.*Prmm1.*r2_4.*t20.*t22.*t_phi_dot4.*t_theta_dot4.*2.0).*-2.0)./(t8+Prmm1.*t19+Prmm2.*t19.*4.0+Prmm3.*t23.*4.0-Prml2.*Prmm1.*r2_4.*2.0);(1.0./t25.^2.*(Fr1_5.*L_vector2_5.*2.0-Fr2_5.*L_vector1_5.*2.0-Prml2.*Prmm1.*d1dot_5.*t26.*t_theta_dot5.*2.0+Prmm1.*d1dot_5.*r2_5.*t26.*t_theta_dot5.*2.0+Prmm2.*d1dot_5.*r2_5.*t26.*t_theta_dot5.*4.0+Prmm3.*d1dot_5.*r3_5.*t26.*t_theta_dot5.*4.0+Prmm3.*d2dot_5.*r3_5.*t26.*t_theta_dot5.*4.0-Prmm1.*t5.*t25.*t27.*t_phi_dot5.*t_theta_dot5-Prmm1.*t24.*t25.*t27.*t_phi_dot5.*t_theta_dot5-Prmm2.*t24.*t25.*t27.*t_phi_dot5.*t_theta_dot5.*4.0-Prmm3.*t25.*t27.*t28.*t_phi_dot5.*t_theta_dot5.*4.0+Prml2.*Prmm1.*r2_5.*t25.*t27.*t_phi_dot5.*t_theta_dot5.*2.0).*-2.0)./(t8+Prmm1.*t24+Prmm2.*t24.*4.0+Prmm3.*t28.*4.0-Prml2.*Prmm1.*r2_5.*2.0);(1.0./t30.^2.*(Fr1_6.*L_vector2_6.*2.0-Fr2_6.*L_vector1_6.*2.0-Prml2.*Prmm1.*d1dot_6.*t31.*t_theta_dot6.*2.0+Prmm1.*d1dot_6.*r2_6.*t31.*t_theta_dot6.*2.0+Prmm2.*d1dot_6.*r2_6.*t31.*t_theta_dot6.*4.0+Prmm3.*d1dot_6.*r3_6.*t31.*t_theta_dot6.*4.0+Prmm3.*d2dot_6.*r3_6.*t31.*t_theta_dot6.*4.0-Prmm1.*t5.*t30.*t32.*t_phi_dot6.*t_theta_dot6-Prmm1.*t29.*t30.*t32.*t_phi_dot6.*t_theta_dot6-Prmm2.*t29.*t30.*t32.*t_phi_dot6.*t_theta_dot6.*4.0-Prmm3.*t30.*t32.*t33.*t_phi_dot6.*t_theta_dot6.*4.0+Prml2.*Prmm1.*r2_6.*t30.*t32.*t_phi_dot6.*t_theta_dot6.*2.0).*-2.0)./(t8+Prmm1.*t29+Prmm2.*t29.*4.0+Prmm3.*t33.*4.0-Prml2.*Prmm1.*r2_6.*2.0)];
